INSERT INTO exercises (exercise_name, category, equipment)
VALUES
('Jumping Jacks', 'Warmup', 'None'),
('Walking Knee Hugs', 'Warmup', 'None'),
('Arm Circles', 'Warmup', 'None'),
('Side Shuffles', 'Warmup', 'None'),
('Backpedaling', 'Warmup', 'None'),
('Lunges', 'Warmup', 'None'),
('Leg Swings', 'Warmup', 'None'),
('Inch Worms', 'Warmup', 'None'),
('Crab Walk', 'Warmup', 'None'),
('Neck Stretch', 'Warmup', 'None'),
('Tricep Stretch', 'Warmup', 'None'),
('Shoulder Stretch', 'Warmup', 'None'),
('Dynamic Chest', 'Warmup', 'None'),
('Mid Back Turn', 'Warmup', 'None'),
('Hip Circles', 'Warmup', 'None'),
('Toe Touches', 'Warmup', 'None'),
('Neck Tilts', 'Warmup', 'None'),
('Arnold Press', 'Upper', 'Dumbbells'),
('Axe Hold', 'Upper', 'Dumbbells'),
('Barbell Ab Rollout', 'Abs', 'Barbell'),
('Barbell Hack Squats', 'Lower', 'Barbell'),
('Barbell Lunges', 'Lower', 'Barbell'),
('Barbell Tricep Extension', 'Upper', 'Barbell'),
('Bear Walk', 'All', 'Gym Mat'),