INSERT IGNORE INTO exercises (exercise_name, category, equipment)
VALUES
('Jumping Jacks', 'Warmup', 'None'),
('Walking Knee Hugs', 'Warmup', 'None'),
('Arm Circles', 'Warmup', 'None'),
('Side Shuffles', 'Warmup', 'None'),
('Backpedaling', 'Warmup', 'None'),
('Lunges', 'Warmup', 'None'),
('Leg Swings', 'Warmup', 'None'),
('Inch Worms', 'Warmup', 'None'),
('Crab Walk', 'Warmup', 'None'),
('Neck Stretch', 'Warmup', 'None'),
('Tricep Stretch', 'Warmup', 'None'),
('Shoulder Stretch', 'Warmup', 'None'),
('Dynamic Chest', 'Warmup', 'None'),
('Mid Back Turn', 'Warmup', 'None'),
('Hip Circles', 'Warmup', 'None'),
('Toe Touches', 'Warmup', 'None'),
('Neck Tilts', 'Warmup', 'None'),
('Arnold Press', 'Upper', 'Dumbbells'),
('Axe Hold', 'Upper', 'Dumbbells'),
('Barbell Ab Rollout', 'Abs', 'Barbell'),
('Barbell Hack Squats', 'Lower', 'Barbell'),
('Barbell Lunges', 'Lower', 'Barbell'),
('Barbell Tricep Extension', 'Upper', 'Barbell'),
('Bear Walk', 'All', 'Gym Mat'),
('Bench Press', 'Upper', 'Bench'),
('Bench Press - Narrow Grip', 'Upper', 'Bench'),
('Bent Over Lateral Raises', 'Upper', 'Dumbbells'),
('Dumbbell High Pulls', 'Upper', 'Dumbbells'),
('Bent Over Row - Barbell', 'Upper', 'Barbell'),
('Bent Over Row - Dumbbells', 'Upper', 'Dumbbells'),
('Bent Over Row - Reverse Grip', 'Upper', 'Barbell'),
('Bicep Curls - Barbell', 'Upper', 'Barbell'),
('Bicep Curls - Dumbbells', 'Upper', 'Dumbbells'),
('Bicep Curls - EZ-Bar', 'Upper', 'EZ-Bar'),
('Push-Ups', 'Upper', 'None'),
('Calf Raises', 'Lower', 'Dumbbells'),
('Pull-Ups', 'Upper', 'Pull-up Bar'),
('Chin-Ups', 'Upper', 'Pull-up Bar'),
('Crunches', 'Abs', 'None'),
('Incline Dumbbell Curls', 'Upper', 'Incline Bench'),
('Elbow to Knee Crunch', 'Abs', 'None'),
('Deadlift', 'All', 'Barbell'),
('Decline Bench Press - Barbell', 'Upper', 'Incline Bench'),
('Decline Bench Press - Dumbbell', 'Upper', 'Incline Bench'),
('Decline Push-Ups', 'Upper', 'Bench'),
('Deficit Deadlift', 'All', 'Barbell'),
('Diagonal Shoulder Press', 'Upper', 'Kettlebells'),
('Dips', 'All', 'None'),
('Dips With Benches', 'Upper', 'Bench'),
('Dumbbell Curls', 'Upper', 'Dumbbells'),
('Kettlebell Squat', 'Lower', 'Kettlebells'),
('Dumbbell Lunges', 'Lower', 'Dumbbells'),
('Dumbbell Tricep Extension', 'Upper', 'Dumbbells'),
('Skull Crushers - Dumbell', 'Upper', 'Dumbbells'),
('Skull Crushers - EZ-Bar', 'Upper', 'EZ-Bar'),
('Front Raises', 'Upper', 'Dumbbells'),
('Sit Outs', 'All', 'None'),
('Handstand Push-Ups', 'Upper', 'None'),
('Hip Raises', 'Lower', 'None'),
('Hip Thrusts', 'Lower', 'Bench'),
('Hollow Hold', 'Abs', 'None'),
('Incline Bench Press - Barbell', 'Upper', 'Incline Bench'),
('Incline Bench Press - Dumbbell', 'Upper', 'Incline Bench'),
('Incline Dumbbell Flys', 'Upper', 'Incline Bench'),
('Isometric Wipers', 'Upper', 'None'),
('Leg Raises', 'Lower', 'None'),
('Shoulder Press', 'Upper', 'Barbell'),
('Muscle-Ups', 'All', 'Pull-up Bar'),
('Plank', 'Abs', 'None'),
('Row - Barbell', 'Upper', 'Barbell'),
('Row - EZ-Bar', 'Upper', 'EZ-Bar'),
('Side Crunches', 'Abs', 'None'),
('Side Plank', 'Abs', 'None'),
('Squat Thrusts', 'All', 'None'),
('Superman', 'All', 'None'),
('Incline Push-Ups', 'Upper', 'Bench'),
('Spiderman', 'Abs', 'None'),
('Wall Push-Ups', 'Upper', 'None'),
('Wall Slides', 'Lower', 'None'),
('Wall Squat', 'Abs', 'None'),
('Mountian Climbers', 'Abs', 'Medicine Ball'),
('Overhead Squats', 'Abs', 'Medicine Ball'),
('Circles', 'Upper', 'Medicine Ball'),
('Russian Twist', 'Abs', 'Gym Mat'),
('Russian Twist - Medicine Ball', 'Abs', 'Medicine Ball'),
('Side Lunges', 'Lower', 'Medicine Ball'),
('Slams', 'All', 'Medicine Ball');